spring:
  application:
    name: sellorder
  datasource:
    url: jdbc:mysql://192.168.43.201:3306/demo?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    host: 192.168.43.201
    port: 6379
  rabbitmq:
    host: 192.168.43.201
    port: 5672
    username: guest
    password: guest
env: dev2
