spring:
  datasource:
    url: jdbc:mysql://192.168.8.100:3306/demo?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    host: 192.168.8.100
    port: 6379
